### ISSUE TITLE
Variable names `x` and `x_match` in the same table

### ISSUE THREAD

**Issue by MariusMerkleQC** [Quantco/sqlcompyre#6]
When there exists a variable named `x` and `x_match` in the same table, then the comparison fails. I think this happens as `sqlcompyre` suffixes variables with `_match` internally (https://github.com/Quantco/sqlcompyre/blob/main/sqlcompyre/analysis/table_comparison.py#L260).

**Comment by borchero** [comment]
Fixed by #13
